### ISSUE TITLE
What mAP boost did you get with Yolov3 + CIoU on MS COCO dataset?

### ISSUE THREAD

**Issue by AlexeyAB** [Zzh-tju/DIoU-darknet#1]
@csdwren @Zzh-tju Hi,
Excellent work!

What mAP (0.5, 0.75, 0.5...0.95) boost did you get with Yolov3 + CIoU on MS COCO dataset?

**Comment by Zzh-tju** [comment]
We are stepping up the experiment on COCO, the result is coming soon.
