### ISSUE TITLE
VOC 评估

### ISSUE THREAD

**Issue by zZTaccount** [Zzh-tju/DIoU-darknet#10]
非常感谢您的贡献！
但是在使用darknet对数据集进行评估的时候我感到有一些迷惑，在readme中VOC的evaluation有这段话，"There will be 20 txt files generated in results/.
Then for validation, I mainly use three files: compute_mAP.py, voc_eval.py, map.py"，但是好像没有看到这三个文件在哪里。您可以告知一下完整的测试流程么，非常感谢！

**Comment by Zzh-tju** [comment]
谢谢你的提醒，VOC评估方法已更新在新增文件夹eval，以及readme中

**Comment by zZTaccount** [comment]
谢谢您的及时回复，另外我还有一点问题，我在测试COCO 2017 val数据集时得到results.json文件有一亿多行，这是正常的吗？内容基本如下：
![image](https://user-images.githubusercontent.com/38245299/71167761-3fd85a80-2290-11ea-890b-4db1ac1298b4.png)

我获取results.json的命令是‘./darknet detector valid cfg/coco-ciou.dada cfg/coco-ciou.cfg backup/ciou.weights’ ，请问是需要添加threshold还是哪里的配置不对么？

**Comment by Zzh-tju** [comment]
COCO我用的是2014val

**Comment by zZTaccount** [comment]
嗯嗯，但是2017和2014应该没有太大差别，我生成results.json之后使用coco_eval.py，程序会在‘cocoDt=cocoGt.loadRes(resfile)’这句代码执行过程中自己崩掉，感觉是因为results.json太大了导致，可以麻烦您帮我看下我的配置是否有问题吗？ 
coco-ciou.data内容如下:
classes=80
train=train.txt
valid=/home/projects/DIoU-darknet/val2017.txt
names=data/coco.names
backup=backup/ciou
eval=coco
其中val2017.txt的内容是5000张验证集图片的绝对路径。

**Comment by Zzh-tju** [comment]
不行，darknet貌似只能用2014

**Comment by zZTaccount** [comment]
噢噢好的，那我试一下2014吧，再次感谢~
