### ISSUE TITLE
Gradient calculation problem of DIoU

### ISSUE THREAD

**Issue by AdonisGe** [Zzh-tju/DIoU-darknet#14]
When calculating the DIoU gradient, I think it should be the sum of the two numerators around line 504 to 505 (and also line 510 to 511) of the source file box.c .

for e.g. `p_dx += (2*(truth.x-pred.x)*C-(2*Cw*dCw_dx+2*Ch*dCh_dx)*S) / (C * C);` 
             should be `p_dx += (2*(truth.x-pred.x)*C+(2*Cw*dCw_dx+2*Ch*dCh_dx)*S) / (C * C);`

Is it a typo or I have got it wrong?

**Comment by Zzh-tju** [comment]
you can check the caculation of dCw_dx. And -1*dCw_dx corresponds to its moving direction for x.
