### ISSUE TITLE
单GPU训练的时候avg很大

### ISSUE THREAD

**Issue by SkeletonOne** [Zzh-tju/DIoU-darknet#18]
例如 在第15step输出的结果 avg是680多，这样正常吗？
15: 825.548706, 680.210022 avg, 0.000000 rate, 10.086429 seconds, 960 images

此外，单gpu的话，需要训练多久，训练保存的模型存放在哪呢？

谢谢！

**Comment by Zzh-tju** [comment]
请放上完整的输出看看
VOC07+12 16551张图片双1080Ti训练25小时，你可以估算一下训练时间

**Comment by SkeletonOne** [comment]
@Zzh-tju 一开始用voc_ciou.cfg就比较大，我换成了mse 但是还是这个状态

我截取了一小段，麻烦你看下是否正常？

v3 (mse loss, Normalizer: (iou: 0.500000, cls: 1.000000) Region 82 Avg (IOU: 0.255062, CIOU: 0.224703), Class: 0.497592, Obj: 0.471005, No Obj: 0.464764, .5R: 0.200000, .75R: 0.000000, count: 5
v3 (mse loss, Normalizer: (iou: 0.500000, cls: 1.000000) Region 94 Avg (IOU: 0.096293, CIOU: 0.084972), Class: 0.103786, Obj: 0.595780, No Obj: 0.500441, .5R: 0.000000, .75R: 0.000000, count: 1
v3 (mse loss, Normalizer: (iou: 0.500000, cls: 1.000000) Region 106 Avg (IOU: -nan, CIOU: -nan), Class: -nan, Obj: -nan, No Obj: 0.442706, .5R: -nan, .75R: -nan, count: 0
train_network_err: 6738.515625
v3 (mse loss, Normalizer: (iou: 0.500000, cls: 1.000000) Region 82 Avg (IOU: 0.386918, CIOU: 0.365564), Class: 0.315161, Obj: 0.534498, No Obj: 0.465729, .5R: 0.428571, .75R: 0.000000, count: 7
v3 (mse loss, Normalizer: (iou: 0.500000, cls: 1.000000) Region 94 Avg (IOU: 0.149495, CIOU: 0.091475), Class: 0.792503, Obj: 0.163358, No Obj: 0.499790, .5R: 0.000000, .75R: 0.000000, count: 1
v3 (mse loss, Normalizer: (iou: 0.500000, cls: 1.000000) Region 106 Avg (IOU: -nan, CIOU: -nan), Class: -nan, Obj: -nan, No Obj: 0.442664, .5R: -nan, .75R: -nan, count: 0
train_network_err: 6732.281738
v3 (mse loss, Normalizer: (iou: 0.500000, cls: 1.000000) Region 82 Avg (IOU: 0.242412, CIOU: 0.199615), Class: 0.429557, Obj: 0.444653, No Obj: 0.464992, .5R: 0.142857, .75R: 0.000000, count: 7
v3 (mse loss, Normalizer: (iou: 0.500000, cls: 1.000000) Region 94 Avg (IOU: 0.493805, CIOU: 0.485426), Class: 0.534075, Obj: 0.411869, No Obj: 0.499637, .5R: 0.000000, .75R: 0.000000, count: 1
v3 (mse loss, Normalizer: (iou: 0.500000, cls: 1.000000) Region 106 Avg (IOU: -nan, CIOU: -nan), Class: -nan, Obj: -nan, No Obj: 0.441552, .5R: -nan, .75R: -nan, count: 0
train_network_err: 6729.550781
v3 (mse loss, Normalizer: (iou: 0.500000, cls: 1.000000) Region 82 Avg (IOU: 0.365708, CIOU: 0.349141), Class: 0.487167, Obj: 0.383882, No Obj: 0.466945, .5R: 0.333333, .75R: 0.000000, count: 6
v3 (mse loss, Normalizer: (iou: 0.500000, cls: 1.000000) Region 94 Avg (IOU: 0.230210, CIOU: 0.223946), Class: 0.489665, Obj: 0.643842, No Obj: 0.499073, .5R: 0.000000, .75R: 0.000000, count: 1
v3 (mse loss, Normalizer: (iou: 0.500000, cls: 1.000000) Region 106 Avg (IOU: -nan, CIOU: -nan), Class: -nan, Obj: -nan, No Obj: 0.440481, .5R: -nan, .75R: -nan, count: 0
train_network_err: 6702.234375
train_network sum: 108059.843750 / 64
64: 1688.435059, 1354.498047 avg, 0.000000 rate, 21.285235 seconds, 4096 images
Loaded: 0.000095 seconds

**Comment by Zzh-tju** [comment]
很正常，训练VOC刚开始的时候都是好几千的loss，到后面会逐渐降低到1以下。一共5w轮

**Comment by SkeletonOne** [comment]
@Zzh-tju 是双卡50000还是单卡50000呢？

**Comment by Zzh-tju** [comment]
Darknet好像跟gpu数量没有关系，iteration都是一样的

**Comment by SkeletonOne** [comment]
@Zzh-tju 哦哦懂了，我还以为设定的是gpu和batch size成正比。谢谢！
