### ISSUE TITLE
Are there training codes in this project?

### ISSUE THREAD

**Issue by xxAna** [Zzh-tju/DIoU-darknet#21]
Thank you so much for your sharing. And I wonder if the training code of yolo is in this project. I have read your REANDME carefully and can't find the description of how to train the yolo on COCO. Am I missing somthing important? Waiting for your reply. Best wishes!

**Comment by Zzh-tju** [comment]
updated readme.
For more information, you can refer to GIoU (https://github.com/generalized-iou/g-darknet) and original YOLOv3 (https://pjreddie.com/darknet/)

**Comment by xxAna** [comment]
OK. Thank you for your reply.
