### ISSUE TITLE
windows

### ISSUE THREAD

**Issue by Lucky466** [Zzh-tju/DIoU-darknet#3]
Does the job support windows?

**Comment by Zzh-tju** [comment]
No, for windows you can link to https://github.com/AlexeyAB/darknet. This repository already has DIoU and CIoU.

**Comment by Lucky466** [comment]
Sorry,I just find the giou implemention, DIoU  and CIoU are not found

**Comment by Zzh-tju** [comment]
OK, I just saw DIoU and CIoU in src/box.c.

在 2019-12-05 20:55:04，Lucky466 <notifications@github.com> 写道：
Sorry,I just find the giou implemention, DIoU and CIoU are not found

**Comment by Lucky466** [comment]
thank you for your reply!
