### ISSUE TITLE
你好ap怎样得到的呢？

### ISSUE THREAD

**Issue by henbucuoshanghai** [Zzh-tju/DIoU-darknet#36]
按照git的ciou模型，得到最后的ap50，55，60。。
其中ap50.txt，ap75.txt的结果和readmel论文完全一致，但python map.py屏幕显示是54.62
论文里table1左侧的49.21怎样得到的呢  ，diou的呢？
另diou-nms怎样设置的呢？diounms_sort？需要修改的是box_diou的代码？
多谢多谢

**Comment by Zzh-tju** [comment]
确保10个mAP的txt文件放在一个文件夹中，并且没有其他东西。然后再运行`map.py`

要使用DIoU-NMS，只需在cfg里的三个yolo层下设置nms_kind=diounms，详细都写在readme中

**Comment by henbucuoshanghai** [comment]
感谢热心的回复
但是map.py试了很多次    ap75一样 ap50和readme的一样  但终端结果就是54               diou的是50多。。
不懂怎么回事。。

**Comment by Zzh-tju** [comment]
那你只能手动把10个mAP加起来除以10
