### ISSUE TITLE
Some problem about predicted box

### ISSUE THREAD

**Issue by woodenblood** [Zzh-tju/DIoU-darknet#5]
Hi, I trained a net with offical darknet,Then I traied to test this net by your code, But the predicted box always has some error in left top direction, I have checked the code between yours and the official .I didn't found any problem, SO can you help me? Thank you!

**Comment by Zzh-tju** [comment]
you mean the evaluation has error？Actually, the results are the form of x,y,w,h. I suggest to use my weight file provided in readme and test again

**Comment by LeeTaiTai** [comment]
i test your ciou.weights,  get many boxes ,命令： ./darknet detect   cfg/coco-ciou.cfg backup/ciou.weights  data/person.jpg .  why?

**Comment by Zzh-tju** [comment]
can you show me the detect picture？

**Comment by LeeTaiTai** [comment]
自带的data/person.jpg

**Comment by Zzh-tju** [comment]
检测结果有吗

**Comment by LeeTaiTai** [comment]
有结果，出现很多框，但是都不正确。data/person.jpg: Predicted in 9.875581 seconds.
motorbike: 85%
aeroplane: 75%
dog: 82%
frisbee: 91%
surfboard: 83%
diningtable: 76%
keyboard: 85%
teddy bear: 77%
motorbike: 95%
aeroplane: 92%
bench: 80%
dog: 87%
sheep: 84%
bear: 81%
frisbee: 95%
surfboard: 92%
spoon: 83%
bowl: 93%
carrot: 85%
pottedplant: 80%
toilet: 80%
tvmonitor: 92%
keyboard: 91%
clock: 88%
dog: 76%
horse: 77%
cup: 77%
sink: 79%
motorbike: 76%
sink: 76%
motorbike: 81%
dog: 81%
tie: 77%
frisbee: 84%
baseball bat: 76%
surfboard: 77%
bowl: 76%
banana: 79%
carrot: 82%
tvmonitor: 78%
remote: 77%
tie: 77%
toilet: 80%
car: 79%
frisbee: 90%
sofa: 84%
toilet: 75%
parking meter: 80%
frisbee: 86%
pottedplant: 79%
car: 79%
frisbee: 91%
donut: 77%
motorbike: 81%
aeroplane: 79%
frisbee: 83%
bowl: 79%
parking meter: 82%
frisbee: 87%
parking meter: 78%
frisbee: 85%
parking meter: 79%
frisbee: 84%
frisbee: 83%
motorbike: 77%
motorbike: 77%
frisbee: 81%
motorbike: 76%

**Comment by Zzh-tju** [comment]
显然你cfg应该用错了，我的权重是VOC的

**Comment by LeeTaiTai** [comment]
ciou,diou都是用voc 训练的？不是coco数据？那么cfg 的class应该由80改修成20?

**Comment by Zzh-tju** [comment]
对，coco训练时间太长，我们设备紧缺，所以目前只提供了voc的。你换成voc的cfg就可以了

**Comment by LeeTaiTai** [comment]
thanks ,test ok！

**Comment by woodenblood** [comment]
> you mean the evaluation has error？Actually, the results are the form of x,y,w,h. I suggest to use my weight file provided in readme and test again

我用你的代码模型训练过网络，在你的darknet里面测试ok的，但是用官方darknet测试预测框会向左上方偏移，于是今天我用官方darknet训练一个网络，在你的网络测试，结果是向右下方偏移，我已开始感觉是映射的问题，但排查了代码没有发现问题，请问你的实现对于官方darknet有做什么改动吗

**Comment by Zzh-tju** [comment]
@woodenblood 偏移很多吗？只有x,y有偏移，w,h无变化吗

**Comment by woodenblood** [comment]
> @woodenblood 偏移很多吗？只有x,y有偏移，w,h无变化吗

我在get_yolo_box里面打印了未映射回原图之前的网络输出，同一个网络和weights的结果和darknet官方代码不一样，我不懂什么问题。。。xy差别较大，wh差别较小，但是结果很有规律，所有框都朝一个方向偏移。

**Comment by Zzh-tju** [comment]
这种差别是否很大，哪一种更好？我建议你下载GDarknet，看看是否也会这样
