### ISSUE TITLE
如何在windows下训练？

### ISSUE THREAD

**Issue by DataXujing** [Zzh-tju/DIoU-darknet#8]
我直接可以使用 <https://github.com/AlexeyAB/darknet>.  编译的模型在Windows下训练DIoU-darkent吗？

**Comment by Zzh-tju** [comment]
可以，配置相应的cfg应该就可以

**Comment by DataXujing** [comment]
好的，谢谢，配置cfg和DIoU-darknet是相同的对吗？大神?

**Comment by Zzh-tju** [comment]
按照他的来

**Comment by DataXujing** [comment]
好的，非常感谢！
