### ISSUE TITLE
你好，请问DIOU能用到SSD中嘛？

### ISSUE THREAD

**Issue by lofyol** [Zzh-tju/DIoU-darknet#9]

**Comment by Zzh-tju** [comment]
D/C IoU loss 可被嫁接进任何需要做bbox 回归的检测算法中，只要其回归目标是xywh的形式。此外DIoU-NMS也可以短短数行代码集成进任何需要做greedy-NMS的检测器中。一个SSD的实现如下 (https://github.com/Zzh-tju/DIoU-SSD-pytorch).

**Comment by lofyol** [comment]
谢谢
